name: Shell Commands

on:
     push:
        branches: [main]
     pull_request:
        branches: [main]
jobs:
    run-shell-commands:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: echo String
          run:  echo "God made it possible for me"
        - name: Multi-line Script
          run: |
               whoami
                pwd
